python global_cnn.py CLIPSEQ_SFRS1
python multi_channel_cnn.py CLIPSEQ_SFRS1
python global_cnn.py ICLIP_HNRNPC
python multi_channel_cnn.py ICLIP_HNRNPC
python global_cnn.py ICLIP_TDP43
python multi_channel_cnn.py ICLIP_TDP43
python global_cnn.py ICLIP_TIA1
python multi_channel_cnn.py ICLIP_TIA1
python global_cnn.py ICLIP_TIAL1
python multi_channel_cnn.py ICLIP_TIAL1
python global_cnn.py PARCLIP_AGO1234
python multi_channel_cnn.py PARCLIP_AGO1234
python global_cnn.py PARCLIP_ELAVL1
python multi_channel_cnn.py PARCLIP_ELAVL1
python global_cnn.py PARCLIP_ELAVL1A
python multi_channel_cnn.py PARCLIP_ELAVL1A
python global_cnn.py PARCLIP_EWSR1
python multi_channel_cnn.py PARCLIP_EWSR1
python global_cnn.py PARCLIP_FUS
python multi_channel_cnn.py PARCLIP_FUS
python global_cnn.py PARCLIP_HUR
python multi_channel_cnn.py PARCLIP_HUR
python global_cnn.py PARCLIP_IGF2BP123
python multi_channel_cnn.py PARCLIP_IGF2BP123
python global_cnn.py PARCLIP_MOV10_Sievers
python multi_channel_cnn.py PARCLIP_MOV10_Sievers
python global_cnn.py PARCLIP_PUM2
python multi_channel_cnn.py PARCLIP_PUM2
python global_cnn.py PARCLIP_QKI
python multi_channel_cnn.py PARCLIP_QKI
python global_cnn.py PARCLIP_TAF15
python multi_channel_cnn.py PARCLIP_TAF15
python global_cnn.py PTBv1
python multi_channel_cnn.py PTBv1
python global_cnn.py ZC3H7B_Baltz2012
python multi_channel_cnn.py ZC3H7B_Baltz2012
